# PID-Datei nicht in /var/run speichern,
# weil OpenShift dort oft keine Schreibrechte hat
pid /tmp/nginx.pid;

# Pflichtblock für Nginx
events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Temporäre Dateien in /tmp speichern
    # OpenShift erlaubt Schreiben in /tmp
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    server {

        # Nginx lauscht auf Port 8080
        # Üblicher Port für OpenShift-Container
        listen 8080;

        # Hier liegen die Angular Build-Dateien
        root /usr/share/nginx/html;

        # Standard-Datei beim Aufruf der Webseite
        index index.html;

        location / {

            # Angular SPA Routing
            #
            # 1. Prüfe, ob die Datei existiert
            # 2. Prüfe, ob ein Ordner existiert
            # 3. Falls nichts gefunden wird:
            #    index.html zurückgeben
            #
            # Beispiel:
            # /tickets/123
            # -> Angular Router übernimmt
            try_files $uri $uri/ /index.html;
        }
    }
}
