version: '3.8'

services:
  frontend:
    image: frontend-ai-deskhelp:latest  
    ports:
      - "4200:80"

  backend:
    image: backend-ai-deskhelp:latest
    ports:
      - "8089:8089"

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ai_deskhelp
      DB_USER: rashid
      DB_PASSWORD: my-secret-pw

    depends_on:
      - db
  db:
    image: postgres:15
    container_name: ai-deskhelp-db
    restart: always
    environment:
      POSTGRES_DB: ai_deskhelp
      POSTGRES_USER: rashid
      POSTGRES_PASSWORD: my-secret-pw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: ai-deskhelp-pgadmin
    
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      
    ports:
      - "8088:80"



volumes:
  postgres_data:




