-- PostgreSQL schema for ai-helpdesk.
-- Matches the current JPA mappings for users and tickets, and includes the
-- ERD-only ticket_comment and ai_suggestion tables.

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    user_role VARCHAR(255) DEFAULT 'ROLE_USER',
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_user_role CHECK (user_role IN ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE IF NOT EXISTS tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    ticket_status VARCHAR(255) DEFAULT 'OPEN',
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tickets_created_by
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_tickets_ticket_status
        CHECK (ticket_status IN ('OPEN', 'CLOSED', 'IN_PROGRESS'))
);

CREATE INDEX IF NOT EXISTS idx_tickets_created_by
    ON tickets (created_by);

CREATE TABLE IF NOT EXISTS ticket_comment (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ticket_comment_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES tickets (ticket_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ticket_comment_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ticket_comment_ticket_id
    ON ticket_comment (ticket_id);

CREATE INDEX IF NOT EXISTS idx_ticket_comment_user_id
    ON ticket_comment (user_id);

CREATE TABLE IF NOT EXISTS ai_suggestion (
    suggestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    suggestion VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_suggestion_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES tickets (ticket_id)
        ON DELETE CASCADE
);


