apiVersion: apps/v1 # Deployment API
kind: Deployment # Erstellt Pods

metadata:
  name: backend-spring-app # Deployment Name
  labels:
    app: backend-ai-deskhelp-app # App Label
    part: java-spring # Backend Label

spec:
  replicas: 3 # 3 Pods starten

  selector:
    matchLabels:
      app: backend-ai-deskhelp-app # Findet Pods
      part: java-spring # Mit diesem Label

  template: # Pod Vorlage
    metadata:
      labels:
        app: backend-ai-deskhelp-app # Pod Label
        part: java-spring # Pod Label

    spec:
      containers:
        - name: backend-ai-deskhelp # Container Name

          image: backend-ai-deskhelp:latest # Docker Image

          imagePullPolicy: IfNotPresent # Nur laden falls nötig

          ports:
            - containerPort: 8089 # Spring Boot Port
          env:
            - name: DB_HOST
              value: ai-deskhelp-db-service # Service Name

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: ai_deskhelp
            - name: POSTGRES_USER # DB User
              value: rashid

            - name: DB_PASSWORD
              value: my-secret-pw

            - name: OLLAMA_BASE_URL
              value: http://ollama-service:11434
              
---
apiVersion: v1 # Service API
kind: Service # Netzwerkzugriff

metadata:
  name: backend-service # Service Name

  labels:
    app: backend-ai-deskhelp-app # App Label
    part: java-spring # Backend Label

spec:
  type: NodePort # Extern erreichbar

  selector:
    app: backend-ai-deskhelp-app # Verbindet Pods
    part: java-spring # Mit diesen Labels

  ports:
    - port: 8082 # Service Port

      targetPort: 8089 # Weiterleitung zum Container

      nodePort: 30082 # Externer Port
