spring.application.name=ai-helpdesk
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8089

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiModerationAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration

# Secret Key für JWT Tokens
# Spring Boot versucht zuerst die Environment Variable JWT_SECRET zu lesen.
# Falls sie nicht existiert, wird der Default-Wert verwendet.
# Dieser Key wird benutzt, um JWT Tokens zu signieren und zu validieren.
bezkoder.app.jwtSecret=${JWT_SECRET:MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=}

# Ablaufzeit des JWT Tokens in Millisekunden
# Spring Boot nutzt zuerst die Environment Variable JWT_EXPIRATION_MS.
# Falls keine gesetzt ist, gilt der Default-Wert 86400000 ms (= 24 Stunden).
bezkoder.app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL:phi3:mini}
spring.ai.ollama.embedding.model=${OLLAMA_EMBEDDING_MODEL:mxbai-embed-large}

# temporary properties:


logging.level.com.rashid.ai_helpdesk.controller=DEBUG
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.ollama=TRACE
logging.level.org.springframework.ai.vectorstore=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.ai.chat.client.advisor=TRACE


# ----------------------------------------------------
# Spring Boot Actuator Health Checks
# Für Kubernetes / OpenShift
# ----------------------------------------------------

# Aktiviert Readiness- und Liveness-Probes
management.endpoint.health.probes.enabled=true

# Aktiviert den Liveness-Endpunkt
management.health.livenessstate.enabled=true

# Aktiviert den Readiness-Endpunkt
management.health.readinessstate.enabled=true

# Stellt den Health-Endpunkt über HTTP bereit
management.endpoints.web.exposure.include=health